# Definition of ROS service SickLocInitializePose for sick localization
# Automatically adjusts the given input pose according to the map of the environment and the current LiDAR measurements.
# Example call (ROS1):
# rosservice call SickLocInitializePose "{x: 100, y: -100, yaw: 2000, sigmatranslation: 1000}"
# Example call (ROS2):
# ros2 service call SickLocInitializePose sick_scan/srv/SickLocInitializePoseSrv "{x: 100, y: -100, yaw: 2000, sigmatranslation: 1000}"
# 

# 
# Request (input)
# 

int32 x # Vehicle x position relative to map origin. [<min>, <max>] in [mm] 
int32 y # Vehicle y position relative to map origin. [<min>, <max>] in [mm] 
int32 yaw # Vehicle yaw angle relative to map origin. [-180000, 180000] in [mdeg] 
uint32 sigmatranslation # Standard deviation of the initial position describing the uncertainty. [300, 5000] in [mm] 

---

# 
# Response (output)
# 

bool success # true: success response received from localization controller, false: service failed (timeout or error status from controller)
